### ISSUE TITLE
RuntimeError: the derivative for 'target' is not implemented

### ISSUE THREAD

**Issue by zhuyingSeu** [yxgeee/FD-GAN#11]
Thanks for your sharing!
When I ran the train.py and changed the bachsize to 8, the error occured as below.
![problem](https://user-images.githubusercontent.com/37655124/49138898-6b0da600-f32b-11e8-964f-d21037103129.png)
I can not figure out how to solve it.

**Comment by winper001** [comment]
> Thanks for your sharing!
> When I ran the train.py and changed the bachsize to 8, the error occured as below.
> ![problem](https://user-images.githubusercontent.com/37655124/49138898-6b0da600-f32b-11e8-964f-d21037103129.png)
> I can not figure out how to solve it.

hi，do you solve this problem?

**Comment by yxgeee** [comment]
Please check if the `target` is empty or not.

**Comment by mehdirostami** [comment]
I restarted my ipython and it worked.
