### ISSUE TITLE
stageII 

### ISSUE THREAD

**Issue by ahuwangsheng** [yxgeee/FD-GAN#16]
![default](https://user-images.githubusercontent.com/41574731/50965373-bdd2a400-150c-11e9-822e-7edaa3e2c824.PNG)

**Comment by cppntn** [comment]
I've encountered the same error

**Comment by ahuwangsheng** [comment]
> 我遇到了同样的错误

Have you solved your problem

**Comment by yxgeee** [comment]
Please check the key names for `state_dict` and `SiameseNet`, if they begins with `'module.'` or not.

**Comment by ahuwangsheng** [comment]
Do you have any reference materials that you can recommend @yxgeee

**Comment by yxgeee** [comment]
> Do you have any reference materials that you can recommend @yxgeee

You can print the `state_dict.keys()` and `SiameseNet.state_dict().keys()` for reference, the `load_state_dict()` function works when the key names match.

**Comment by ahuwangsheng** [comment]
thank you! @yxgeee
