### ISSUE TITLE
load_state_dict error in stateII

### ISSUE THREAD

**Issue by ahuwangsheng** [yxgeee/FD-GAN#19]
The following figure shows the keys for the model.state_dict saved in stage1
![image](https://user-images.githubusercontent.com/41574731/51302354-0c33f580-1a6d-11e9-8554-809df0ed49b1.png)
The following figure shows the keys for the state_dict loaded in stage11
![image](https://user-images.githubusercontent.com/41574731/51302380-2372e300-1a6d-11e9-94d1-1d276e5549dc.png)

The following figure shows the errors,what should I do?@yxgeee
![image](https://user-images.githubusercontent.com/41574731/51302659-fc68e100-1a6d-11e9-8f2a-22e8c21b5d1e.png)

**Comment by heerduo** [comment]
Hello, I encounter the same problem. Have you solved it?

**Comment by heerduo** [comment]
> The following figure shows the keys for the model.state_dict saved in stage1
> ![image](https://user-images.githubusercontent.com/41574731/51302354-0c33f580-1a6d-11e9-8554-809df0ed49b1.png)
> The following figure shows the keys for the state_dict loaded in stage11
> ![image](https://user-images.githubusercontent.com/41574731/51302380-2372e300-1a6d-11e9-94d1-1d276e5549dc.png)
> 
> The following figure shows the errors,what should I do?@yxgeee
> ![image](https://user-images.githubusercontent.com/41574731/51302659-fc68e100-1a6d-11e9-8f2a-22e8c21b5d1e.png)

Hello, I encounter the same problem. Have you solved it?

**Comment by yxgeee** [comment]
You could kindly use or remove the function `remove_module_key` function (https://github.com/yxgeee/FD-GAN/blob/master/fdgan/model.py#L88) to match the key name of loaded state dict and your model.

**Comment by heerduo** [comment]
Thanks a lot！
