### ISSUE TITLE
FD-GAN cannot be pretrained in stage two

### ISSUE THREAD

**Issue by QingzeYin** [yxgeee/FD-GAN#2]
After testing stage one, when I was doing FD-GAN pretraining in stage two, the error was occurred as shown below:
![screenshot from 2018-10-24 11-26-27](https://user-images.githubusercontent.com/38550460/47410389-3f315a80-d798-11e8-8c8c-237dc660612c.png)
![screenshot from 2018-10-24 11-21-44](https://user-images.githubusercontent.com/38550460/47410394-40fb1e00-d798-11e8-8a50-dba9db025e64.png)
Do you know which part need to be fixed?

**Comment by yxgeee** [comment]
Since you save your baseline model weights in a key named 'state_dict' (https://github.com/yxgeee/FD-GAN/blob/master/baseline.py#L150).

you can just modify no.54 line in your screenshot 
`state_dict = remove_module_key(torch.load(self.opt.netE_pretrain)['state_dict'])`

**Comment by QingzeYin** [comment]
> Since you save your baseline model weights in a key named 'state_dict' (https://github.com/yxgeee/FD-GAN/blob/master/baseline.py#L150).
> 
> you can just modify no.54 line in your screenshot
> `state_dict = remove_module_key(torch.load(self.opt.netE_pretrain)['state_dict'])`

Thanks for your quickly replying :+1:  . I fixed that with this explicit explanation
