### ISSUE TITLE
hi how can i plot the figure 2,3 in the paper

### ISSUE THREAD

**Issue by 2018hello** [yxgeee/FD-GAN#27]
hi, I really like the figure 2,3 in your paper.
how can i plot the figures in the paper?
Can you give me some suggestions?
Thank you so much!!!

**Comment by liulitianji** [comment]
you can do it with visio

**Comment by liulitianji** [comment]
And I have a question for you:"Have you reproduced this code yet? "
IF the answer is "yes",can you share the File structure with me,I really don't known how to reproduced this code.

**Comment by 2018hello** [comment]
Thank you so much!!! But I am sorry that, I just read paper, and don't reproduced this code. Maybe you can ask the author?

**Comment by yxgeee** [comment]
> hi, I really like the figure 2,3 in your paper.
> how can i plot the figures in the paper?
> Can you give me some suggestions?
> Thank you so much!!!

Visio or powerpoint could be applied.
