### ISSUE TITLE
code reproduced  issue

### ISSUE THREAD

**Issue by liulitianji** [yxgeee/FD-GAN#28]
Thanks for your great work first,and this is the first code I reproduce.
So if you don't mind,could you please share the File structure with us? 
Like the specific path of the datasets which i was download from the link you give , such as download the Market1501_baseline_model from baiduyun then unzip it on the path a/b/c .

**Comment by yxgeee** [comment]
You could first clone this repo and then follow the steps starting from https://github.com/yxgeee/FD-GAN#prerequisites
