### ISSUE TITLE
数据包导入问题

### ISSUE THREAD

**Issue by TheBigCock** [yxgeee/FD-GAN#3]
您好，我是在window下运行实验代码的，请问在运行实验的时候我把我的数据包放在了相应的位置为什么还是在报  RuntimeError: Dataset not found or corrupted. Please follow README.md to prepare Market1501 dataset.   这个错误？ 请问能说说具体的位置吗？

**Comment by yxgeee** [comment]
Could you provide more details, e.g. the log screenshots, the dataset path, the running root, etc.

**Comment by TheBigCock** [comment]
Hello, I have not modified the directory in your code, and added the subfolder datasets in the project , and put all the data into this folder.The directory information in opt.txt is as follows:
checkpoints: ./checkpoints/
connect_layers: 0
dataroot: ./datasets/
dataset: Market1501

**Comment by yxgeee** [comment]
Have you `unzip` the datasets?

**Comment by TheBigCock** [comment]
yes,I have unzip them in the  subfolder " datasets " .

**Comment by yxgeee** [comment]
Which directory are you running in?

**Comment by TheBigCock** [comment]
The directory where the project is run is ~/Desktop/FD-GAN-master

**Comment by TheBigCock** [comment]
Hello, I am running under the Linux system, follow the command to put the downloaded and decompressed data set into the datasets file, and then run the following command, there is still an error that the data set can not be found.
maker......:~/Desktop/FD-GAN-master$ python3 baseline.py -b 256 -j 4 -d Market1501 -a resnet50 --combine-trainval --lr 0.01 --epochs 100 --step-size 40 --eval-step 5 --logs-dir ~/checkpoints/
/home/maker/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "baseline.py", line 200, in <module>
    main(parser.parse_args())
  File "baseline.py", line 93, in main
    args.combine_trainval, args.np_ratio)
  File "baseline.py", line 32, in get_data
    dataset = datasets.create(name, root, split_id=split_id)
  File "/home/maker/Desktop/FD-GAN-master/reid/datasets/__init__.py", line 41, in create
    return __factory[name](root, *args, **kwargs)
  File "/home/maker/Desktop/FD-GAN-master/reid/datasets/market1501.py", line 16, in __init__
    "Please follow README.md to prepare Market1501 dataset.")
RuntimeError: Dataset not found or corrupted. Please follow README.md to prepare Market1501 dataset.

**Comment by yxgeee** [comment]
`-d market1501`

(do not use the capital letter)

**Comment by TheBigCock** [comment]
The following error occurred after I modified it.

DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
usage: baseline.py [-h] [-d {Market1501,cuhk03,dukemtmc}] [-b BATCH_SIZE]
                   [-j WORKERS] [--split SPLIT] [--height HEIGHT]
                   [--width WIDTH] [--combine-trainval]
                   [-a {resnet101,resnet152,resnet18,resnet34,resnet50}]
                   [--lr LR] [--np-ratio NP_RATIO] [--momentum MOMENTUM]
                   [--weight-decay WEIGHT_DECAY] [--step-size STEP_SIZE]
                   [--resume PATH] [--evaluate] [--epochs EPOCHS]
                   [--eval-step EVAL_STEP] [--seed SEED] [--data-dir PATH]
                   [--logs-dir PATH]
baseline.py: error: argument -d/--dataset: invalid choice: 'market1501' (choose from 'Market1501', 'cuhk03', 'dukemtmc')

**Comment by yxgeee** [comment]
Do you clone the latest repo or have you modified the code? since I use all small letters for dataset names, refer to https://github.com/yxgeee/FD-GAN/blob/master/reid/datasets/__init__.py#L11

But maybe you can also change the dataset directory name to capital letter for matching.

**Comment by TheBigCock** [comment]
I still have a request. If you are convenient, can you share the trained model in Baidu cloud? Google Cloud's link is invalid, thank you very much, thank you for your patience to help me answer!

**Comment by yxgeee** [comment]
Ok, I will try to share the model in Baidu cloud some days later.

**Comment by TheBigCock** [comment]
> Do you clone the latest repo or have you modified the code? since I use all small letters for dataset names, refer to https://github.com/yxgeee/FD-GAN/blob/master/reid/datasets/__init__.py#L11
> 
> But maybe you can also change the dataset directory name to capital letter for matching.

Thank you,  I downloaded the code directly and did not modify it. Now try to modify the name of the dataset so that the name matches.

**Comment by csqzs** [comment]
>           您好，我是在window下运行实验代码的，请问在运行实验的时候我把我的数据包放在了相应的位置为什么还是在报  RuntimeError: Dataset not found or corrupted. Please follow README.md to prepare Market1501 dataset.   这个错误？ 请问能说说具体的位置吗？
您好 我想问您一下 您的数据集方便分享吗 我在网上下载的数据集没有posefile 等文件

**Comment by yxgeee** [comment]
> I still have a request. If you are convenient, can you share the trained model in Baidu cloud? Google Cloud's link is invalid, thank you very much, thank you for your patience to help me answer!

I have shared the models and datasets on Baidu cloud.
