### ISSUE TITLE
在别的数据集上面训练

### ISSUE THREAD

**Issue by SigmaLGX** [yxgeee/FD-GAN#34]
您好
我想在其他数据集上面进行训练，已经将数据集使用openpose进行处理过，并生成了对应的关键点txt文件。 但是，关于生成 meta.json，split.json，不知道您这边有没有生成脚本呢？ 
目前我的目录结构是：boundingbox_train，boundingbox_test，boundingbox_query

**Comment by yxgeee** [comment]
你好，

生成数据集json的脚本可以参考：
https://github.com/Cysu/open-reid/tree/master/reid/datasets


sigma <notifications@github.com>于2019年10月23日 周三15:50写道：

**Comment by SigmaLGX** [comment]
好的，谢谢！
