### ISSUE TITLE
which distance measure is used?

### ISSUE THREAD

**Issue by MuadDev** [yxgeee/FD-GAN#37]
What is the used distance measure for measuring the distance between the features? Is it euclidean? Because if I use scipy to calculate these distances instead I get very different values.

**Comment by yxgeee** [comment]
The function of measuring feature distance referring to:
https://github.com/yxgeee/FD-GAN/blob/master/reid/evaluators.py#L76

Actually, it is L2-distance, which is the square of Euclidean distance.
