### ISSUE TITLE
NameError:name 'val_loader' is not defined

### ISSUE THREAD

**Issue by haozhihui110** [yxgeee/FD-GAN#38]
Traceback(most recent call last):
  File "train.py" , line in 119, in <module>
     main()
  File "train.py" , line in 97, in main
     mAP = evaluator.evaluate(val_loader, dataset.val, dataset.val, top1=False)

NameError:name 'val_loader' is not defined

**Comment by yxgeee** [comment]
You could simply **change “val_loader” to “test_loader”** for fixing this error, since I forget to define the val_loader in this version of code.

**Comment by yxgeee** [comment]
Or you can define the val_loader by adding 
```
    val_loader = DataLoader(
        Preprocessor(dataset.val,
                     root=dataset.images_dir, transform=test_transformer),
        batch_size=batch_size, num_workers=workers,
        shuffle=False, pin_memory=False)
```

**Comment by haozhihui110** [comment]
> 
> 
> Or you can define the val_loader by adding
> 
> ```
>     val_loader = DataLoader(
>         Preprocessor(dataset.val,
>                      root=dataset.images_dir, transform=test_transformer),
>         batch_size=batch_size, num_workers=workers,
>         shuffle=False, pin_memory=False)
> ```

alright, thank you very much
