### ISSUE TITLE
dataset issues

### ISSUE THREAD

**Issue by csqzs** [yxgeee/FD-GAN#4]
excuse me , I need to generate a pose file after downloading the market1501 set or processing data set? For example, 'images' 'meta.json' 'splits.json' 'poses'  in the code

**Comment by yxgeee** [comment]
You can download the **prepared** datasets with pose files following [README-datasets](https://github.com/yxgeee/FD-GAN#datasets)

**Comment by csqzs** [comment]
![d](https://user-images.githubusercontent.com/44661685/47835584-a629c180-dddf-11e8-9396-e257e743276c.png) This is the directory where I downloaded the dataset. So what you mean is that you also need to download another code link to generate the pose file.

**Comment by yxgeee** [comment]
[Market1501](https://drive.google.com/open?id=1LS5_bMqv-37F14FVuziK63gz0wPyb0Hh)
[DukeMTMC](https://drive.google.com/open?id=1Ujtm-Cq7lpyslBkG-rSBjkP1KVntrgSL)
[CUHK03](https://drive.google.com/open?id=1R7oCwyMHYIxpRVsYm7-2REmFopP9TSXL)

click on the **name** of datasets where you could find a link for downloading

**Comment by csqzs** [comment]
Thank you, it turned out to be my download error. Due to restrictions I didn't open this link, so I downloaded the data set in Baidu Cloud.

**Comment by csqzs** [comment]
If you are convenient, can you share the trained model in Baidu cloud? Google Cloud's link is invalid, thank you very much。

**Comment by yxgeee** [comment]
I will do it some days later.

**Comment by csqzs** [comment]
Thank you very much，I encountered an error in .\FD-GAN-master\reid\evaluation_metrics\classification.py  :{TypeError}sum received an invalid combination of arguments - got (dim=int, keepdim=bool, ), but expected one of:
 * no arguments
 * (int dim)
correct_k = correct[:k].view(-1).float().sum(dim=0, keepdim=True)

**Comment by yxgeee** [comment]
I have not met this error before, maybe you can provide more details.
(ps. If you setup the open-reid in the same environment before, you need to delete the installation files first.)

**Comment by yxgeee** [comment]
> If you are convenient, can you share the trained model in Baidu cloud? Google Cloud's link is invalid, thank you very much。

I have shared the models and datasets on Baidu cloud.

**Comment by csqzs** [comment]
Thank you so much for sharing！ I wish you all the best.
